from django.contrib import admin

# Register your models here.
from ingresos.models import *
from inventario.models import medidor

#admin.site.register(medidor)
admin.site.register(cliente)
admin.site.register(detalleClienteMedidor)
admin.site.register(caserio)
admin.site.register(urbanizacion)
admin.site.register(calle)
admin.site.register(tipoCalle)
admin.site.register(actividad)
admin.site.register(tipoDeConstruccion)
admin.site.register(claseRed)
admin.site.register(calibreDeLaRed)
admin.site.register(estadoDeUnaInstalacion)
admin.site.register(tipoDeAcometidaRed)
admin.site.register(usoDeEnergia)
admin.site.register(usoGeneralDelInmueble)
admin.site.register(usoEspecificoDelInmueble)
admin.site.register(modeloDeMedidor)
admin.site.register(formaDeConexion)
admin.site.register(demanda)
admin.site.register(motivoParaSolicitud)
admin.site.register(tipoDeSolicitud)
admin.site.register(tipoDeServicio)
admin.site.register(ubicacionDelMedidor)
admin.site.register(cuadrilla)
admin.site.register(empleado)
admin.site.register(instalador)
admin.site.register(materialDeActividad)
admin.site.register(detalleDeActividad)
admin.site.register(nivelSocieconomico)
admin.site.register(foto)
admin.site.register(provincia)
admin.site.register(canton)
admin.site.register(ubicacion)
admin.site.register(parroquia)
admin.site.register(sector)
admin.site.register(ruta)
admin.site.register(secuencia)
admin.site.register(detalleClienteReferencia)
admin.site.register(materialDeLaRed)